[build]
  command = "npm install && npm run build"
  functions = "functions"
[[redirects]]
  from = "/api/extension/proxy"
  to = "/.netlify/functions/api/extension/proxy"
  force = false
  status = 200